# Generated by Django 6.0.6 on 2026-09-30 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Examination Title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed examination description / instructions')),
                ('exam_date', models.DateField(help_text='Examination date (YYYY-MM-DD)')),
                ('start_time', models.TimeField(help_text='Examination start time (HH:MM:SS)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Examination duration in minutes (must be > 0)')),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, help_text='Calculated aware start datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, help_text='Calculated aware end datetime', null=True)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', help_text='Current publication status', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='True if published and visible to students')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag to preserve referential integrity for future attempts/results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'ordering': ['-exam_date', '-start_time', '-created_at'],
                'indexes': [models.Index(fields=['exam_date', 'start_time'], name='examination_exam_da_cbd16e_idx'), models.Index(fields=['start_datetime', 'end_datetime'], name='examination_start_d_803114_idx'), models.Index(fields=['is_published', 'is_deleted'], name='examination_is_publ_60eb55_idx')],
            },
        ),
    ]
